# Generated by Django 5.0.2 on 2024-02-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('posts', '0005_alter_like_unique_together'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_slug', models.SlugField(blank=True)),
                ('post_text', models.CharField(max_length=3000)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_top_post', models.BooleanField(default=False)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('posted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('tags', models.ManyToManyField(to='tag.tag')),
            ],
        ),
    ]
