# Generated by Django 5.0.2 on 2024-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
