# Generated by Django 5.0.2 on 2024-03-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_commented_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_premium_post',
            field=models.BooleanField(default=False),
        ),
    ]
