# Generated by Django 5.0.2 on 2024-03-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_imgae',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
