# Generated by Django 5.0.2 on 2024-03-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_post_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_imgae',
            new_name='post_image',
        ),
    ]
