# Generated by Django 5.0.2 on 2024-04-08 06:52

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=django_quill.fields.QuillField(),
        ),
    ]
