# Generated by Django 5.0.2 on 2025-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
