# Generated by Django 5.0.2 on 2024-04-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(choices=[('Size', 'Size'), ('Phone Model', 'Phone Model'), ('Material', 'Material')], max_length=255),
        ),
    ]
