# Generated by Django 5.0.2 on 2025-08-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_order_is_paid_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'online'), ('cod', 'cod')], default='cod', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('Dispatched', 'dispatched'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled')], default='Pending', max_length=255),
        ),
    ]
