# Generated by Django 5.0.2 on 2024-03-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_premiumuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumuser',
            name='has_active_subscription',
        ),
    ]
